### PR TITLE
Missing codeword_ptr increment in codewords_to_bytes

### PR DESCRIPTION
**Pull request by dangrie158**
After each whole block that gets decoded as a byte the codeword_ptr is missing an increment. This causes the code to interpret the last codeword in the byte block as a command < 900 and switches to text mode.

This commit adds the missing increment and can successfully decode a longer barcode with lots of mode switches between byte and text modes

### CODE REVIEW

**Comment by dangrie158** [comment]
A little bit more information. For privacy reasons I can't share the test barcodes I tested this with, however after instrumenting the `codewords_to_data` function this is the output before the change:


```
Byte 6    @022 - 047 Bytespace:    0 - 30 ending with 900 @ 027 but next codeword is 398 @ 022
Text      @027 - 032 Bytespace:   30 - 40 ending with 900 @ 027 but next codeword is 900 @ 027
Text      @033 - 038 Bytespace:   40 - 48 ending with 901 @ 033 but next codeword is 901 @ 033
Byte      @043 - 054 Bytespace:   48 - 61 ending with 900 @ 045 but next codeword is 784 @ 043
Text      @045 - 047 Bytespace:   61 - 65 ending with 900 @ 045 but next codeword is 900 @ 045
Text      @071 - 096 Bytespace:   65 - 112 ending with 901 @ 071 but next codeword is 901 @ 071
Byte      @189 - 334 Bytespace:  112 - 285 ending with 901 @ 217 but next codeword is 477 @ 189
Text      @217 - 245 Bytespace:  285 - 333 ending with 901 @ 217 but next codeword is 901 @ 217
Byte      @237 - 260 Bytespace:  333 - 360 ending with 901 @ 241 but next codeword is 784 @ 237
Text      @241 - 245 Bytespace:  360 - 368 ending with 901 @ 241 but next codeword is 901 @ 241
Byte      @264 - 291 Bytespace:  368 - 400 ending with 901 @ 269 but next codeword is 189 @ 264
Text      @269 - 274 Bytespace:  400 - 410 ending with 901 @ 269 but next codeword is 901 @ 269
Byte      @277 - 285 Bytespace:  410 - 419 ending with 901 @ 278 but next codeword is 068 @ 277
Text      @278 - 279 Bytespace:  419 - 421 ending with 901 @ 278 but next codeword is 901 @ 278
Byte      @370 - 483 Bytespace:  421 - 556 ending with 901 @ 392 but next codeword is 018 @ 370
Text      @392 - 414 Bytespace:  556 - 597 ending with 901 @ 392 but next codeword is 901 @ 392
Byte      @432 - 480 Bytespace:  597 - 654 ending with 901 @ 441 but next codeword is 858 @ 432
Text      @441 - 450 Bytespace:  654 - 671 ending with 901 @ 441 but next codeword is 901 @ 441
Byte      @447 - 453 Bytespace:  671 - 678 ending with 901 @ 448 but next codeword is 120 @ 447
Text      @448 - 449 Bytespace:  678 - 680 ending with 901 @ 448 but next codeword is 901 @ 448
Byte      @456 - 464 Bytespace:  680 - 689 ending with 901 @ 457 but next codeword is 068 @ 456
Text      @457 - 458 Bytespace:  689 - 691 ending with 901 @ 457 but next codeword is 901 @ 457
Byte      @549 - 662 Bytespace:  691 - 826 ending with 901 @ 571 but next codeword is 607 @ 549
Text      @571 - 593 Bytespace:  826 - 868 ending with 901 @ 571 but next codeword is 901 @ 571
Byte      @579 - 587 Bytespace:  868 - 877 ending with 901 @ 580 but next codeword is 068 @ 579
Text      @580 - 581 Bytespace:  877 - 879 ending with 901 @ 580 but next codeword is 901 @ 580
Byte      @586 - 592 Bytespace:  879 - 886 ending with 901 @ 587 but next codeword is 068 @ 586
Text      @587 - 588 Bytespace:  886 - 888 ending with 901 @ 587 but next codeword is 901 @ 587
Byte      @595 - 603 Bytespace:  888 - 897 ending with 901 @ 596 but next codeword is 068 @ 595
Text      @596 - 597 Bytespace:  897 - 899 ending with 901 @ 596 but next codeword is 901 @ 596
Byte      @602 - 608 Bytespace:  899 - 906 ending with 901 @ 603 but next codeword is 068 @ 602
Text      @603 - 604 Bytespace:  906 - 908 ending with 901 @ 603 but next codeword is 901 @ 603
Byte      @611 - 619 Bytespace:  908 - 917 ending with 901 @ 612 but next codeword is 068 @ 611
Text      @612 - 613 Bytespace:  917 - 919 ending with 901 @ 612 but next codeword is 901 @ 612
Byte      @618 - 624 Bytespace:  919 - 926 ending with 900 @ 619 but next codeword is 068 @ 618
Text      @619 - 620 Bytespace:  926 - 928 ending with 900 @ 619 but next codeword is 900 @ 619
Text      @628 - 636 Bytespace:  928 - 938 ending with 924 @ 628 but next codeword is 924 @ 628
Byte 6    @633 - 638 Bytespace:  938 - 944 ending with 901 @ 634 but next codeword is 812 @ 633
Text      @634 - 635 Bytespace:  944 - 945 ending with 901 @ 634 but next codeword is 901 @ 634
Byte      @641 - 648 Bytespace:  945 - 953 ending with 901 @ 642 but next codeword is 068 @ 641
Text      @642 - 643 Bytespace:  953 - 955 ending with 901 @ 642 but next codeword is 901 @ 642
Byte      @649 - 656 Bytespace:  955 - 963 ending with 900 @ 650 but next codeword is 068 @ 649
Text      @650 - 651 Bytespace:  963 - 965 ending with 900 @ 650 but next codeword is 900 @ 650
Text      @656 - 661 Bytespace:  965 - 975 ending with 924 @ 656 but next codeword is 924 @ 656
Byte 6    @661 - 666 Bytespace:  975 - 981 ending with 900 @ 662 but next codeword is 812 @ 661
Text      @662 - 663 Bytespace:  981 - 982 ending with 900 @ 662 but next codeword is 900 @ 662
Text      @668 - 673 Bytespace:  982 - 992 ending with 924 @ 668 but next codeword is 924 @ 668
Byte 6    @673 - 678 Bytespace:  992 - 998 ending with 900 @ 674 but next codeword is 812 @ 673
Text      @674 - 675 Bytespace:  998 - 999 ending with 900 @ 674 but next codeword is 900 @ 674
Text      @680 - 685 Bytespace:  999 - 1009 ending with 924 @ 680 but next codeword is 924 @ 680
Byte 6    @685 - 690 Bytespace: 1009 - 1015 ending with 900 @ 686 but next codeword is 812 @ 685
Text      @686 - 687 Bytespace: 1015 - 1016 ending with 900 @ 686 but next codeword is 900 @ 686
Text      @692 - 697 Bytespace: 1016 - 1026 ending with 901 @ 692 but next codeword is 901 @ 692
Byte      @695 - 697 Bytespace: 1026 - 1028 ending with 900 @ 695 but next codeword is 900 @ 695
```

and this after the change:


```
Byte 6    @027 - 052 Bytespace:    0 - 30 ending with 900 @ 027 but next codeword is 900 @ 027
Text      @033 - 038 Bytespace:   30 - 38 ending with 901 @ 033 but next codeword is 901 @ 033
Byte      @045 - 056 Bytespace:   38 - 51 ending with 900 @ 045 but next codeword is 900 @ 045
Text      @071 - 096 Bytespace:   51 - 98 ending with 901 @ 071 but next codeword is 901 @ 071
Byte      @217 - 362 Bytespace:   98 - 271 ending with 901 @ 217 but next codeword is 901 @ 217
Byte      @241 - 264 Bytespace:  271 - 298 ending with 901 @ 241 but next codeword is 901 @ 241
Byte      @269 - 296 Bytespace:  298 - 330 ending with 901 @ 269 but next codeword is 901 @ 269
Byte      @278 - 286 Bytespace:  330 - 339 ending with 901 @ 278 but next codeword is 901 @ 278
Byte      @392 - 505 Bytespace:  339 - 474 ending with 901 @ 392 but next codeword is 901 @ 392
Byte      @441 - 489 Bytespace:  474 - 531 ending with 901 @ 441 but next codeword is 901 @ 441
Byte      @448 - 454 Bytespace:  531 - 538 ending with 901 @ 448 but next codeword is 901 @ 448
Byte      @457 - 465 Bytespace:  538 - 547 ending with 901 @ 457 but next codeword is 901 @ 457
Byte      @571 - 684 Bytespace:  547 - 682 ending with 901 @ 571 but next codeword is 901 @ 571
Byte      @580 - 588 Bytespace:  682 - 691 ending with 901 @ 580 but next codeword is 901 @ 580
Byte      @587 - 593 Bytespace:  691 - 698 ending with 901 @ 587 but next codeword is 901 @ 587
Byte      @596 - 604 Bytespace:  698 - 707 ending with 901 @ 596 but next codeword is 901 @ 596
Byte      @603 - 609 Bytespace:  707 - 714 ending with 901 @ 603 but next codeword is 901 @ 603
Byte      @612 - 620 Bytespace:  714 - 723 ending with 901 @ 612 but next codeword is 901 @ 612
Byte      @619 - 625 Bytespace:  723 - 730 ending with 900 @ 619 but next codeword is 900 @ 619
Text      @628 - 636 Bytespace:  730 - 740 ending with 924 @ 628 but next codeword is 924 @ 628
Byte 6    @634 - 639 Bytespace:  740 - 746 ending with 901 @ 634 but next codeword is 901 @ 634
Byte      @642 - 649 Bytespace:  746 - 754 ending with 901 @ 642 but next codeword is 901 @ 642
Byte      @650 - 657 Bytespace:  754 - 762 ending with 900 @ 650 but next codeword is 900 @ 650
Text      @656 - 661 Bytespace:  762 - 772 ending with 924 @ 656 but next codeword is 924 @ 656
Byte 6    @662 - 667 Bytespace:  772 - 778 ending with 900 @ 662 but next codeword is 900 @ 662
Text      @668 - 673 Bytespace:  778 - 788 ending with 924 @ 668 but next codeword is 924 @ 668
Byte 6    @674 - 679 Bytespace:  788 - 794 ending with 900 @ 674 but next codeword is 900 @ 674
Text      @680 - 685 Bytespace:  794 - 804 ending with 924 @ 680 but next codeword is 924 @ 680
Byte 6    @686 - 691 Bytespace:  804 - 810 ending with 900 @ 686 but next codeword is 900 @ 686
Text      @692 - 697 Bytespace:  810 - 820 ending with 901 @ 692 but next codeword is 901 @ 692
Byte      @695 - 697 Bytespace:  820 - 822 ending with 900 @ 695 but next codeword is 900 @ 695
```

**Comment by dangrie158** [comment]
I just added a simple test case for decoding byte mode blocks. The test case for binary data that was already available (using the `binary_data.png`) contains only a single byte-shifted byte but no block where the mode is switched to byte mode:

```
GLI CS    @003 - 030 Bytespace:    0 - 0 ending with 913 @ 029 but next codeword is 477 @ 003
Text      @029 - 055 Bytespace:    0 - 43 ending with 913 @ 029 but next codeword is 913 @ 029
Byte Shift@031 - 055 Bytespace:   43 - 44 ending with 900 @ 054 but next codeword is 782 @ 031
Text      @054 - 077 Bytespace:   44 - 82 ending with 900 @ 054 but next codeword is 900 @ 054
```

**Comment by tbrettallen** [comment]
Great catch! Thanks for your contribution.

I'll go ahead and get this merged and update the package on pypi!

**Comment by dangrie158** [comment]
Thank you for your work and the fast response :)

**Comment by tbrettallen** [comment]
Fix merged and deployed in version 1.0.5

**Pull request merged**
